name: Deploy API

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies
        run: npm install

      - name: Deploy to VM
        run: |
          ssh azureuser@20.55.97.67 <<EOF
            cd index.js  # Replace with your directory on server
            pm2 start index.js  # Assuming you use pm2 for process management
          EOF

      - name: Notify on failure
        uses: actions/github-script@v6
        if: failure()
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Deployment failed!'
            })
