name: Deploy API

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Deploy to VM
        uses: actions/ssh@v3
        with:
          host: 20.55.97.67
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Replace with actual secret name
          script: |
            # Replace with generic deployment commands (assuming SCP for file transfer)
            scp -i ~/.ssh/azureuser index.js/* user@host:/target/directory  # Adjust target directory path

            # Replace with commands to start your server process on the VM
            ssh -i ~/.ssh/id_rsa_vm user@host 'nohup node index.js &'  # Assuming Node.js and nohup for background execution

      - name: Notify on failure
        uses: actions/github-script@v6
        if: failure()
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Deployment failed!'
            })
