name: Deploy to VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
      
           
            # Assuming Node.js and PM2 are installed on the VM
            node index.js

      - name: Verify Deployment (Optional)
        run: ssh ${{ secrets.HOST }}@${{ secrets.USER_NAME }} 
